name: Github Action Demo
on: push
jobs:
  Premier-job:
    name: Premier job
    runs-on: Ubuntu-latest
    steps:
      - run: echo "Premier job"
      - run: echo "Fin premier job"
  Second-job:
    name: Second job
    runs-on: Ubuntu-latest
    needs: Premier-job
    steps:
      - run: echo "Second job"
      - run: echo "Fin second job"
